include: package:flutter_lints/flutter.yaml
formatter:
  trailing_commas: preserve

analyzer:
  errors:
    body_might_complete_normally_nullable: ignore
  plugins:
    - custom_lint
  exclude:
    - "**/*.g.dart"