name: cinebox
description: "Aplicativo de filmes usando o TMDB"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  envied: ^1.3.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.1
  riverpod_annotation: ^3.0.1
  retrofit: ^4.6.0
  logger: ^2.6.0
  json_annotation: ^4.9.0
  dio: ^5.9.0
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^3.0.1
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.1
  envied_generator: ^1.3.0
  retrofit_generator: ^10.0.0
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_gen:
  output: lib/ui/core/themes
